const AUTH_MAIL_TYPE_LIST = 'AUTH_MAIL_TYPE_LIST';
const AUTH_MAIL_LIST = 'AUTH_MAIL_LIST';
const SYST_MAIL_ACCOUNTS = 'SYST_MAIL_ACCOUNTS';

module.exports = {
  AUTH_MAIL_TYPE_LIST,
  AUTH_MAIL_LIST,
  SYST_MAIL_ACCOUNTS,
};
