const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;
const LOCKED = 423;
const TOO_MANY_REQUESTS = 429;

const SERVICE_UNAVAILABLE = 503;

export {
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  LOCKED,
  TOO_MANY_REQUESTS,

  SERVICE_UNAVAILABLE,
};
